version: 2
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: "install runtime dependencies"
          command: |
            make setup
            make install

      - run:
          name: "install test dependencies"
          requires:
              - run
          command: |
            make test-setup

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - test:
          name: "test code"
          requires:
            - run
          command: |
            . .venv/bin/activate
            make lint
