DNS:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneName: tk.
    Comment: Weighted RR for my frontends.
    RecordSets:
    - Name: capstoneprojectwebpageforsubmission.tk.
      Type: CNAME
      TTL: '900'
      SetIdentifier: Frontend One
      Weight: '0'
      ResourceRecords:
      - Fn::ImportValue: !Sub "${EnvironmentA}-LB-DNS-NAME"
    - Name: capstoneprojectwebpageforsubmission.tk.
      Type: CNAME
      TTL: '900'
      SetIdentifier: Frontend Two
      Weight: '10'
      ResourceRecords:
      - Fn::ImportValue: !Sub "${EnvironmentB}-LB-DNS-NAME"
