####################################################
# Udacity Project 2 - Deploy WebApp Cloudformation #
####################################################

Description: >
  Author: Nicolas Neuburger / Udacity Nanodegree Cloud DevOps Engineer
  Purpose: > Project 2 - Deployment WebApp using CloudFormation
            > Contains cloudformation configuration for the cloud's permissions


Parameters:
  EnvironmentName:
      Description: An environment name that will be prefixed to resou
      Type: String
      Default: UdacityProject

Resources:
  UdacityS3ReadOnlyEC2:
      Type: AWS::IAM::Role
      Properties:
          RoleName: !Join ["", [!Sub "${EnvironmentName}", "UdacityS3ReadOnlyEC2"]]
          AssumeRolePolicyDocument:
              Statement:
              - Action: ['sts:AssumeRole']
                Effect: Allow
                Principal:
                    Service: [ec2.amazonaws.com]
          Policies:
              - PolicyName: "S3ReadOnly"
                PolicyDocument:
                    Statement:
                    - Action:
                        - "s3:List*"
                        - "s3:Get*"
                      Effect: Allow
                      Resource: "*"
  RoleAnsibleMaster:
      Type: AWS::IAM::Role
      Properties:
          RoleName: !Join ["", [!Sub "${EnvironmentName}", "RoleAnsibleMaster"]]
          AssumeRolePolicyDocument:
              Statement:
              - Action: ['sts:AssumeRole']
                Effect: Allow
                Principal:
                    Service: [ec2.amazonaws.com]
          ManagedPolicyArns:
              - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess


  InstanceProfileWebserver:
      Type: AWS::IAM::InstanceProfile
      DependsOn: UdacityS3ReadOnlyEC2
      Properties:
          InstanceProfileName: !Sub "${EnvironmentName}-InstanceProfileWebserver"
          Roles:
              - !Join ["", [!Sub "${EnvironmentName}", "UdacityS3ReadOnlyEC2"]]
  InstanceProfileAnsibleMaster:
      Type: AWS::IAM::InstanceProfile
      DependsOn: RoleAnsibleMaster
      Properties:
          InstanceProfileName: !Sub "${EnvironmentName}-InstanceProfileAnsibleMaster"
          Roles:
              - !Join ["", [!Sub "${EnvironmentName}", "RoleAnsibleMaster"]]

Outputs:
  InstanceProfileWebserver:
      Description: IAM Instance Profile defined for the WebApp to contact S3 services
      Value:  !Sub "${EnvironmentName}-InstanceProfileWebserver"
      Export:
        Name: !Sub "${EnvironmentName}-IAM-INST-APP"
  InstanceProfileWebserver:
      Description: ARN of IAM Instance Profile defined for the WebApp to contact S3 services
      Value: !GetAtt "InstanceProfileWebserver.Arn"
      Export:
        Name: !Sub "${EnvironmentName}-IAM-INST-APP-ARN"
  InstanceProfileAnsibleMaster:
      Description: IAM Instance Profile defined for the Ansible Master for EC2
      Value:  !Sub "${EnvironmentName}-InstanceProfileAnsibleMaster"
      Export:
        Name: !Sub "${EnvironmentName}-IAM-INST-ANS-MASTER"
