version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/app

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: "Install Build Dependencies"
          command: |
            export PROJECT_ROOT=${CIRCLE_WORKING_DIRECTORY}
            make install
      - run:
          name: "list files"
          command: 'ls -ap | egrep "^\..*/$"'
      - persist_to_workspace:
          root: ~/app
          paths:
            - .venv_build
  test:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: "Install Test Dependencies"
          command: |
            make test-install
            source .venv_test/bin/activate
            make test-lint

workflows:
  version: 2
  development:
    jobs:
      - build:
          context: app-development
      - test:
          context: app-development
          requires:
            - build
