- hosts: tag_JenkinsServer_true
  become: yes
  tasks:
    - name: Install via apt
      apt:
        name:
          - docker.io
          - wget
          - openjdk-8-jre
        update_cache: false

    - name: add user mod
      command: sudo usermod -aG docker ubuntu

    - name: Unconditionally reboot the machine with all defaults
      reboot:
        reboot_timeout: 3600

    - name: install APT Transport HTTPS
      apt:
        name: apt-transport-https
        state: present

    - name: add Kubernetes apt-key
      apt_key:
        url: http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
        state: present
    # Add source repository into sources list.
    - apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: jenkins
        update_cache: true

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        allow_unauthenticated: yes

    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Sleep for 30 seconds and continue with play
      wait_for: timeout=30

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Print init password Jenkins
      debug:
        var: result.stdout

    #- name: Install Jenkins plugin - Blue Ocean
    #  jenkins_plugin:
    #     name: blueocean

    #- name: Install Jenkins plugin - Credentials Plugin
    #  jenkins_plugin:
    #     name: credentials-plugin
