- hosts: tag_KubernetesMaster_true
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: tag_KubernetesWorker_true
  become: yes
  tasks:
    - name: join cluster
      with_items: "{{ groups['tag_KubernetesMaster_true'] }}"
      shell: "{{ hostvars[item].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
~
