apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    name: static-webpage
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
